#!/bin/bash
# run.sh — start the Yamaha R-N500 controller server
#
# Usage:
#   ./run.sh              — auto-detect: HTTPS if certs exist, else HTTP
#   ./run.sh --https      — force HTTPS (error if no certs found)
#   ./run.sh --http       — force plain HTTP (ignores any certs)
#   ./run.sh --port 9000  — custom port (default: 8080)
#   ./run.sh --help       — show this help
#
# TLS certs are generated by:  ./setup.sh --https
# Cert files are auto-detected by the pattern:  192.168.*.pem / *-key.pem
#
# PWA install (add to home screen) requires HTTPS on desktop browsers.
# On Android Chrome, HTTP on LAN also works.
#
set -e
cd "$(dirname "$0")"

FORCE_HTTPS=""   # "yes" | "no" | "" = auto
PORT=8080

while [[ $# -gt 0 ]]; do
  case "$1" in
    --https)   FORCE_HTTPS="yes"; shift ;;
    --http)    FORCE_HTTPS="no";  shift ;;
    --port)    PORT="$2"; shift 2 ;;
    --help|-h)
      sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown option: $1  (try --help)"; exit 1 ;;
  esac
done

source venv/bin/activate

# ── Detect TLS certs ─────────────────────────────────────────────────────────
CERT=$(ls 192.168.*.pem 2>/dev/null | grep -v '\-key' | head -1 || true)
KEY=$(ls 192.168.*-key.pem 2>/dev/null | head -1 || true)
CERTS_OK=0
[[ -n "$CERT" && -n "$KEY" ]] && CERTS_OK=1

# ── Decide HTTP vs HTTPS ──────────────────────────────────────────────────────
USE_HTTPS=0
if [[ "$FORCE_HTTPS" == "yes" ]]; then
  if [[ $CERTS_OK -eq 0 ]]; then
    echo "❌  No TLS certs found. Generate them first:"
    echo "    ./setup.sh --https"
    exit 1
  fi
  USE_HTTPS=1
elif [[ "$FORCE_HTTPS" == "no" ]]; then
  USE_HTTPS=0
else
  # Auto: use HTTPS if certs are present
  USE_HTTPS=$CERTS_OK
fi

# ── Print access URL ──────────────────────────────────────────────────────────
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
LOCAL_HOST=$(hostname 2>/dev/null || echo "")
PROTO="http"
[[ $USE_HTTPS -eq 1 ]] && PROTO="https"

echo ""
echo "  Yamaha R-N500 Controller"
echo "  ─────────────────────────────────────────"
if [[ $USE_HTTPS -eq 1 ]]; then
  echo "  🔒  HTTPS  (cert: $CERT)"
else
  echo "  🌐  HTTP"
fi
echo ""
echo "  Access via:"
echo "    ${PROTO}://${LOCAL_IP}:${PORT}"
[[ -n "$LOCAL_HOST" ]] && echo "    ${PROTO}://${LOCAL_HOST}:${PORT}"
echo ""
if [[ $USE_HTTPS -eq 0 && $CERTS_OK -eq 0 ]]; then
  echo "  💡  For PWA install on desktop: ./setup.sh --https  then  ./run.sh"
fi
echo "  Press Ctrl+C to stop"
echo "  ─────────────────────────────────────────"
echo ""

# ── Start server ──────────────────────────────────────────────────────────────
if [[ $USE_HTTPS -eq 1 ]]; then
  exec uvicorn app.main:app --host 0.0.0.0 --port "$PORT" \
    --ssl-certfile "$CERT" --ssl-keyfile "$KEY"
else
  exec uvicorn app.main:app --host 0.0.0.0 --port "$PORT"
fi
